seed = {start = 1, step = 1, end = 1000}
nsubj = {start = 5, step = 5, end = 100}
nitem = {start = 2, step = 4, end = 100}
beta = [[2.0, 0.5]]
sigmaranef = [
        {subj = [0.0, 6.0]}
]
sigmares = [0.0001]
noisetype = "pink"
noiselevel = [8.0, 4.0]
models = [["lmmperm", "twostage"]]
