seed = {start = 1, step = 1, end = 1000}
nsubj = {start = 3, step = 2, end = 50}
nitem = {start = 2, step = 2, end = 50}
beta = [[2.0, 0.5]]
sigmaranef = [
        #{subj = [0.0, 0.0]},
        #{subj = [0.0, 0.1]},{subj = [0.0, 0.3]},{subj = [0.0, 0.5]},{subj = [0.0, 1.0]},
        {subj = [1.0, 2.0]},{subj = [1.0, 1.0]},{subj = [1.0, 0.5]},
]
sigmares = [0.0001]
noisetype = "pink"
noiselevel = [2.0, 1.0]
models = [["lmmperm", "twostage"]]
