seed = {start = 1, step = 1, end = 10}
nsubj = {start = 2, step = 1, end = 2}
nitem = {start = 2, step = 2, end = 2}
beta = [[2.0, 0.5]]
sigmaranef = [{subj = [0.0, 0.0]}]
sigmares = 0.0001
noisetype = "white"
noiselevel = 2.0